version: '3'

services:
  spring-app:
    image: mahdifersi/mahdifersi-5se3-g2-khaddem:latest
    container_name: spring-app
    ports:
      - "8070:8070"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/khaddemApp?useUnicode=true&createDatabaseIfNotExist=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=khaddemApp
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
