version: "3"
services:
  mysqldb:
    container_name: mysqldb
    image:  mysql/mysql-server:8.0
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=khaddemApp
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
    networks:
      - my-network

  spring_app:
    image: nourajimi/nourajimi_5se3-g2-khaddem
    container_name: khaddemProject
    environment:
      - spring.datasource.url=jdbc:mysql://localhost:3306/khaddemApp?useUnicode=true&createDatabaseIfNotExist=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    ports:
      - 8070:8070
    depends_on:
      - mysqldb
    networks:
      - my-network
networks:
  my-network:  # Declaration of the 'docker-workshop-network' network
    driver: bridge  # Specify the driver for the network

volumes:
  db:  # Declaration of the 'db' volume
